theme: jekyll-theme-slate
name: T3Discord
title: T3 Discord Bot
description: Find out about all the commands
avatar: https://typo3.org/typo3conf/ext/t3olayout/Resources/Public/Images/Template/typo3_nomargins.svg